import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {

    docs: [
        'study/introduction',
        {
            type: 'category',
            label: 'gof-design-patterns',
            link: {
                type: 'generated-index',
            },
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'study/gof-design-patterns',
                },
            ],
        },
        {
            type: 'category',
            label: 'domain-driven-design',
            link: {
                type: 'generated-index',
            },
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'study/domain-driven-design',
                },
            ],
        },
    ],
    service: [
        'service/introduction',
        {
            type: 'category',
            label: 'dodal-dodal',
            link: {
                type: 'generated-index',
            },
            collapsed: false,
            items: [
                {
                    type: 'autogenerated',
                    dirName: 'service/dodal-dodal',
                },
            ],
        },
    ]
};

export default sidebars;
